// Generated by CoffeeScript 1.9.2
(function(win) {
  'use strict';
  var $df, $doc, $loc, $nav, $scr, $win, defaults, fd, result, webanalyser;
  defaults = require('defaults');
  fd = require('flashdetect');
  $win = win;
  $doc = $win.document;
  $nav = $win.navigator;
  $scr = $win.screen;
  $loc = $win.location;
  $df = {
    sr: $scr.width + "x" + $scr.height,
    vp: $scr.availWidth + "x" + $scr.availHeight,
    sd: $scr.colorDepth,
    je: $nav.javaEnabled ? ($nav.javaEnabled() ? 1 : 0) : 0,
    ul: $nav.languages ? $nav.languages[0] : $nav.language || $nav.userLanguage || $nav.browserLanguage
  };

  /**
   * webanalyser
   */
  webanalyser = (function() {
    function webanalyser() {}

    webanalyser.prototype.getResult = function() {
      var rst;
      if ($df.z == null) {
        rst = {
          dr: $doc.referrer,
          dh: $loc.hostname,
          z: new Date().getTime()
        };
        if (fd.installed) {
          rst.fl = fd.major + " " + fd.minor + " " + fd.revisionStr;
        }
        $df = defaults(rst, $df);
      }
      $df.dl = $loc.href;
      $df.dt = $doc.title;
      return $df;
    };

    webanalyser.prototype.getWindowSize = function() {
      var rst;
      rst = {
        w: 0,
        h: 0
      };
      if (typeof $win.innerWidth === 'number') {
        rst.w = $win.innerWidth;
        rst.h = $win.innerHeight;
      } else if ($doc.documentElement && ($doc.documentElement.clientWidth || $doc.documentElement.clientHeight)) {
        rst.w = $doc.documentElement.clientWidth;
        rst.h = $doc.documentElement.clientHeight;
      } else if ($doc.body && ($doc.body.clientWidth || $doc.body.clientHeight)) {
        rst.w = $doc.body.clientWidth;
        rst.h = $doc.body.clientHeight;
      }
      return rst;
    };

    return webanalyser;

  })();
  result = new webanalyser();
  return module.exports = result;
})(window);
